language: python
python:
  - 2.7
  - 3.6

install: 
  - pip install -r requirements.txt
  - python setup.py install

script: python -W ignore tests/run_all_tests.py

branches:
  except:
  - ContractionDescriptors

notification:
  email: false 
