language: python
python:
  - 2.7
  - 3.6

install: 
  - pip install -r requirements.txt
  - python setup.py install

script: 
  - python tests/run_all_tests.py
  - python examples/test_examples.py

notification:
  email: false
